autocommit

diff --git a/.local/bin/git-remote-gcrypt b/.local/bin/git-remote-gcrypt
--- a/.local/bin/git-remote-gcrypt
+++ b/.local/bin/git-remote-gcrypt
@@ -18,7 +18,6 @@
 # See README.rst for usage instructions
 
 set -e # errexit
-set -u # nounset
 set -f # noglob
 set -C # noclobber
 
@@ -31,6 +30,7 @@ Manifestfile=91bd0c092128cf2e60e1a608c31e92caf1f9c1595f83f2890ef17c0e4881aa0a
 Hex40="[a-f0-9]"
 Hex40=$Hex40$Hex40$Hex40$Hex40$Hex40$Hex40$Hex40$Hex40
 Hex40=$Hex40$Hex40$Hex40$Hex40$Hex40 # Match SHA-1 hexdigest
+GPG="$(git config --get "gpg.program" '.+' || echo gpg)"
 
 Did_find_repo=  # yes for connected, no for no repo
 Localdir="${GIT_DIR:=.git}/remote-gcrypt"
@@ -177,8 +177,10 @@ update_tree()
 {
 	local tab_="	"
 	# $2 is a filename from the repo format
-	(git ls-tree "$1" | xgrep -v -E '\b'"$2"'$';
-		xecho "100644 blob $3$tab_$2") | git mktree
+	(set +e;
+		git ls-tree "$1" | xgrep -v -E '\b'"$2"'$';
+		xecho "100644 blob $3$tab_$2"
+	) | git mktree
 }
 
 # Put giturl $1, file $2
@@ -313,14 +315,14 @@ CLEAN_FINAL()
 
 ENCRYPT()
 {
-	gpg --batch --force-mdc --compress-algo none --trust-model=always --passphrase-fd 3 -c 3<<EOF
+	rungpg --batch --force-mdc --compress-algo none --trust-model=always --passphrase-fd 3 -c 3<<EOF
 $1
 EOF
 }
 
 DECRYPT()
 {
-	gpg -q --batch --no-default-keyring --secret-keyring /dev/null \
+	rungpg -q --batch --no-default-keyring --secret-keyring /dev/null \
 		--keyring /dev/null --passphrase-fd 3 -d  3<<EOF
 $1
 EOF
@@ -333,7 +335,7 @@ PRIVENCRYPT()
 	if isnonnull "$Conf_signkey"; then
 		set -- "$@" -u "$Conf_signkey"
 	fi
-	gpg --batch --compress-algo none --trust-model=always -se "$@"
+	rungpg --compress-algo none --trust-model=always -se "$@"
 }
 
 # $1 is the match for good signature, $2 is the textual signers list
@@ -341,7 +343,7 @@ PRIVDECRYPT()
 {
 	local status_=
 	exec 4>&1 &&
-	status_=$(gpg  --status-fd 3 -q -d 3>&1 1>&4) &&
+	status_=$(rungpg --status-fd 3 -q -d 3>&1 1>&4) &&
 	xfeed "$status_" grep "^\[GNUPG:\] ENC_TO " >/dev/null &&
 	(xfeed "$status_" grep -e "$1" >/dev/null || {
 		echo_info "Failed to verify manifest signature!" &&
@@ -353,15 +355,27 @@ PRIVDECRYPT()
 # Generate $1 random bytes
 genkey()
 {
-	gpg --armor --gen-rand 1 "$1"
+	rungpg --armor --gen-rand 1 "$1"
 }
 
 gpg_hash()
 {
 	local hash_=
-	hash_=$(gpg --with-colons --print-md "$1" | tr A-F a-f)
+	hash_=$(rungpg --with-colons --print-md "$1" | tr A-F a-f)
 	hash_=${hash_#:*:}
 	xecho "${hash_%:}"
+}
+
+rungpg()
+{
+	# gpg will fail to run when there is no controlling tty,
+	# due to trying to print messages to it, even if a gpg agent is set
+	# up. --no-tty fixes this.
+	if [ "x$GPG_AGENT_INFO" != "x" ]; then
+		${GPG} --no-tty "$@"
+	else
+		${GPG} "$@"
+	fi
 }
 
 # Pass the branch/ref by pipe to git
@@ -393,6 +407,8 @@ read_config()
 		git config --path user.signingkey || :)
 	conf_part=$(git config --get "remote.$NAME.gcrypt-participants" '.+' ||
 		    git config --get gcrypt.participants '.+' || :)
+	Conf_pubish_participants=$(git config --get --bool "remote.$NAME.gcrypt-publish-participants" '.+' ||
+		git config --get --bool gcrypt.publish-participants || :)
 
 	# Figure out which keys we should encrypt to or accept signatures from
 	if isnull "$conf_part" || iseq "$conf_part" simple
@@ -407,11 +423,11 @@ read_config()
 
 	for recp_ in $conf_part
 	do
-		gpg_list=$(gpg --with-colons --fingerprint -k "$recp_")
+		gpg_list=$(rungpg --with-colons --fingerprint -k "$recp_")
 		filter_to @r_keyinfo "pub*" "$gpg_list"
 		filter_to @r_keyfpr "fpr*" "$gpg_list"
 		isnull "$r_keyinfo" || isnonnull "${r_keyinfo##*"$Newline"*}" ||
-		#echo_info "WARNING: '$recp_' matches multiple keys, using one"
+		echo_info "WARNING: '$recp_' matches multiple keys, using one"
 		isnull "$r_keyfpr" || isnonnull "${r_keyfpr##*"$Newline"*}" ||
 		echo_info "WARNING: '$recp_' matches multiple fingerprints, using one"
 		r_keyinfo=${r_keyinfo%%"$Newline"*}
@@ -427,7 +443,13 @@ read_config()
 		}
 		# Check 'E'ncrypt capability
 		cap_=$(xfeed "$r_keyinfo" cut -f 12 -d :)
-		iseq "${cap_#*E}" "$cap_" || Recipients="$Recipients -r $keyid_"
+		if ! iseq "${cap_#*E}" "$cap_"; then
+			if [ "$Conf_pubish_participants" = true ]; then
+				Recipients="$Recipients -r $keyid_"
+			else
+				Recipients="$Recipients -R $keyid_"
+			fi
+		fi
 	done
 
 	if isnull "$Recipients"
@@ -484,7 +506,12 @@ ensure_connected()
 	tmp_manifest="$Tempdir/maniF"
 	GET "$URL" "$Manifestfile" "$tmp_manifest" 2>/dev/null || {
 		echo_info "Repository not found: $URL"
-		return 0
+		if ! isnull "$Repoid"; then
+			echo_info "..but repository ID is set. Aborting."
+			return 1
+		else
+			return 0
+		fi
 	}
 
 	Did_find_repo=yes
@@ -796,7 +823,7 @@ setup()
 	trap cleanup_tmpfiles EXIT
 	trap 'exit 1' 1 2 3 15
 
-	#echo_info "Development version -- Repository format MAY CHANGE"
+	echo_info "Development version -- Repository format MAY CHANGE"
 }
 
 # handle git-remote-helpers protocol
@@ -865,6 +892,7 @@ then
 	URL=$2
 	setup
 	ensure_connected
+	git remote remove $NAME 2>/dev/null || true
 	if iseq "$Did_find_repo" "no"
 	then
 		exit 100
